### ISSUE TITLE
confirm: will timeOffRequests crash the app if no pending time off requests are found?

### ISSUE THREAD

**Issue by tongxiang** [CrisisTextLine/Elmer#26]

**Comment by tongxiang** [comment]
```
/Users/tongxiang/ctl/Elmer/jobs/scheduling/TimeOffRequests.js:59
                response.shifts.forEach(function(shift) {
                               ^

TypeError: Cannot read property 'forEach' of undefined
    at /Users/tongxiang/ctl/Elmer/jobs/scheduling/TimeOffRequests.js:59:32
    at Request._callback (/Users/tongxiang/ctl/Elmer/node_modules/wheniwork-unofficial/index.js:159:13)
    at Request.self.callback (/Users/tongxiang/ctl/Elmer/node_modules/wheniwork-unofficial/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/tongxiang/ctl/Elmer/node_modules/wheniwork-unofficial/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/tongxiang/ctl/Elmer/node_modules/wheniwork-unofficial/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
```
